name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v3

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: setup versioning
      id: vars
      run: |
        build_date="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        build_version="$(date -u +'%Y-%m-%d')"
        echo "build_date=$build_date" >> $GITHUB_OUTPUT
        echo "build_version=$build_version" >> $GITHUB_OUTPUT

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.cpu
        build-args: |
          BUILD_DATE=${{ steps.vars.outputs.build_date }}
          BUILD_VERSION=${{ steps.vars.outputs.build_version }}
        push: true
        tags: |
          siutin/stable-diffusion-webui-docker:latest-cpu
          siutin/stable-diffusion-webui-docker:cpu-${{ steps.vars.outputs.build_version }}
        platforms: linux/amd64,linux/arm64
      
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.cuda
        build-args: |
          BUILD_DATE=${{ steps.vars.outputs.build_date }}
          BUILD_VERSION=${{ steps.vars.outputs.build_version }}
        push: true
        tags: |
          siutin/stable-diffusion-webui-docker:latest-cuda
          siutin/stable-diffusion-webui-docker:cuda-${{ steps.vars.outputs.build_version }}
        platforms: linux/amd64
