name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: setup versioning
      id: vars
      run: |
        echo "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
        echo "build_version="$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .        
        file: Dockerfile
        build-args: |
          BUILD_DATE=${{ steps.vars.outputs.build_date }}
          BUILD_VERSION=${{ steps.vars.outputs.build_version }}
        push: true
        tags: siutin/stable-diffusion-webui-docker:${{ steps.vars.outputs.build_version }}
