name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      branch_or_tag:
        description: 'Branch or Tag to build'
        required: true
        default: 'master'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Frees Disk Space (Ubuntu)
      # For more info about this task, see https://github.com/uab-cgds-worthey/quac/issues/78
      uses: jlumbroso/free-disk-space@v1.2.0
      with:
        # this might remove tools that are actually needed, when set to "true"
        tool-cache: true
          
    - name: Checkout Project
      uses: actions/checkout@v3

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: setup versioning
      id: vars
      run: |
        build_date="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        build_version="$(date -u +'%Y-%m-%d')"
        echo "build_date=$build_date" >> $GITHUB_OUTPUT
        echo "build_version=$build_version" >> $GITHUB_OUTPUT

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.cpu
        build-args: |
          BRANCH_OR_TAG=${{ github.event.inputs.branch_or_tag }}
          BUILD_DATE=${{ steps.vars.outputs.build_date }}
          BUILD_VERSION=${{ steps.vars.outputs.build_version }}
        push: true
        tags: |
          siutin/stable-diffusion-webui-docker:latest-cpu
          siutin/stable-diffusion-webui-docker:cpu-${{ github.event.inputs.branch_or_tag }}-${{ steps.vars.outputs.build_version }}
        platforms: linux/amd64,linux/arm64
      
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.cuda
        build-args: |
          BRANCH_OR_TAG=${{ github.event.inputs.branch_or_tag }}
          BUILD_DATE=${{ steps.vars.outputs.build_date }}
          BUILD_VERSION=${{ steps.vars.outputs.build_version }}
        push: true
        tags: |
          siutin/stable-diffusion-webui-docker:latest-cuda
          siutin/stable-diffusion-webui-docker:cuda-${{ github.event.inputs.branch_or_tag }}-${{ steps.vars.outputs.build_version }}
        platforms: linux/amd64
